image: node:16

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/

deploy:
  stage: deploy
  script:
    - npm install -g netlify-cli
    - netlify deploy --dir=build --prod --auth=$NETLIFY_AUTH_TOKEN
  only:
    - main  # or the branch you want to deploy
