stages:
  - deploy

deploy_to_netlify:
  image: node:14
  stage: deploy
  script:
    - npm install -g netlify-cli
    - npm install
    - npm run build
    - netlify deploy --auth $NETLIFY_AUTH_TOKEN --prod --dir=build
  only:
    - main  # or specify the branch you want to deploy
