const API_BASE_URL = process.env.REACT_APP_API_BASE_URL;
const API3_BASE_URL = process.env.REACT_APP_API3_BASE_URL;
const API1_BASE_URL = process.env.REACT_APP_API1_BASE_URL;

export { API_BASE_URL, API3_BASE_URL, API1_BASE_URL };